// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhixvkgdxmcnlypfesuh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhoaXh2a2dkeG1jbmx5cGZlc3VoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4Njk1MjksImV4cCI6MjA2OTQ0NTUyOX0.ibLZZHMwnc7-UKe4tULDxyZS7Hka8PiJjoz_OvGpRPI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});